## Conda environment for the course "Statistical Analysis with R" 
## of the "Diplome Universitaire en Bioinformatique integrative" (DU-Bii).
## https://du-bii.github.io/accueil/
name: dubii_r_2019

channels:
  - conda-forge
  - bioconda/label/gcc7       # To get R > 3.5
  - bioconda
  - default
  - lcantini

dependencies:

  ## RCRAN packages
  - conda-forge::r-knitr        # For R markdown
  - conda-forge::r-kableextra   # To export nice-looking tables in the R markdown reports
  - conda-forge::r-formattable  # nice formating of tables in reports
  - conda-forge::r-roxygen2     # To build package documentation
  - conda-forge::r-yaml         # Required to load Yaml config files
  - conda-forge::r-e1071        # for SVM
  - conda-forge::r-randomforest # Supervised classification
  - conda-forge::r-tidyverse    # Collection of R packages designed for data science (ggplot2, tidyr, dplyr, readr, purr, tibble, strigr, forcats)
  - bioconda::r-factominer   # For PCA
  - conda-forge::r-factoextra   # To plot PCA output
  - conda-forge::r-cowplot      # Add-on to ggplot2 for enhance design
  - conda-forge::r-corrplot     # Graphical display of a correlation matrix, confidence interval
  
  ## Bioconductor packages
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger 
  - bioconda::bioconductor-limma
  - bioconda::r-mixomics # For the course of integrative bioinformatics
  
  ## Other packages
  - lcantini::r-mofa
