## Conda environment for the course "Statistical Analysis with R" 
## of the "Diplome Universitaire en Bioinformatique integrative" (DU-Bii).
## https://du-bii.github.io/accueil/
name: dubii_m3_stat_r-2020

channels:
  - bioconda
  - conda-forge
  - r

dependencies:

  ## RCRAN packages
  ## Note: whenever possible, Gildas recommends to use the conda-forge 
  ## rather than the r channel in Anaconda Cloud (https://anaconda.org/)
  - conda-forge::r-base  >=3.6
  - conda-forge::r-knitr        # For R markdown
  - conda-forge::r-kableextra   # To export nice-looking tables in the R markdown reports
  - conda-forge::r-formattable  # nice formating of tables in reports
  - conda-forge::r-roxygen2     # To build package documentation
  - conda-forge::r-yaml         # Required to load Yaml config files
  - conda-forge::r-e1071        # for SVM
  - conda-forge::r-randomforest # Supervised classification
  - conda-forge::r-tidyverse    # Collection of R packages designed for data science (ggplot2, tidyr, dplyr, readr, purr, tibble, strigr, forcats)
  - conda-forge::r-factominer   # For PCA
  - conda-forge::r-factoextra   # To plot PCA output
  - conda-forge::r-rpart        # To compute rpart modele
  - conda-forge::r-rpart.plot   # To visualize rpart modele
  - conda-forge::r-caret        # To supervised classification
  - conda-forge::r-cowplot      # Add-on to ggplot2 for enhanced design
  - conda-forge::r-corrplot     # Graphical display of a correlation matrix, confidence interval
#  - conda-forge::r-momr         # Analysis of metagenomic data
  - conda-forge::r-gridExtra    # Graphical display of several plots
  - conda-forge::r-ade4         # PCoA
  - conda-forge::r-vegan        # Distances calculations
  - conda-forge::r-ggpubr       # Stats on the graphs
  - conda-forge::r-clues        # For clustering
  - conda-forge::r-gprofiler    # functional enrichment 
  - conda-forge::r-vioplot      # Violin plots
  - conda-forge::r-sm            # undeclared dependency of vioplot


  ## Bioconda packages
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger 
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-qvalue
  - bioconda::bioconductor-multtest
  - bioconda::bioconductor-recount # used to generate the TCGA study case
  - bioconda::r-classdiscovery
  - bioconda::r-momr
  - bioconda::bioconductor-complexheatmap

